#!/usr/local/bin/php -f
<?php
// basic heads up example

namespace RPurinton\poker;

$build_info = json_decode(file_get_contents('build_info.json'), true);
echo ("poker (cli) v" . $build_info["number"] . " (built: " . $build_info["date"] . ")\n");

require_once('src/Casino.php');
$casino = new Casino("My Casino");
$table = $casino->add_table(new Table([
    "id" => 1,
    "name" => "My Table",
    "seats" => 3,
]));
$player1 = $casino->add_player(new Player("Russell", PlayerType::HUMAN));
$casino->buy_chips($player1, 10000);
$table->seat_player($player1, $table->seats[0])->buy_chips(1000);
$player2 = $casino->add_player(new Player("Lily", PlayerType::HUMAN));
$casino->buy_chips($player2, 10000);
$table->seat_player($player2, $table->seats[1])->buy_chips(1000);
for ($i = 0; $i < 3; $i++) {
    $table->new_hand();
}
foreach ($table->seats as $seat) $seat->cash_out();
foreach ($casino->players as $player) $casino->cash_out($player);
//print_r($table->chat_history);
