#!/usr/local/bin/php -f
<?php
// basic heads up example

namespace RPurinton\poker;

require_once(__DIR__ . '/vendor/autoload.php');

$build_info = json_decode(file_get_contents('build_info.json'), true);
echo ("poker (cli) v" . $build_info["number"] . " (built: " . $build_info["date"] . ")\n");

require_once('src/Casino.php');
$casino = new Casino("My Casino");
$table = $casino->add_table(new Table([
    "id" => 1,
    "name" => "My Table",
    "seats" => 3,
]));

$player1 = $casino->add_player(new Player("Russell", PlayerType::HUMAN));
$casino->buy_chips($player1, 1000);
$table->seat_player($player1, $table->seats[1])->buy_chips(1000);

$player2 = $casino->add_player(new Player("Lily", PlayerType::AI));
$casino->buy_chips($player2, 1000);
$table->seat_player($player2, $table->seats[2])->buy_chips(1000);

$player3 = $casino->add_player(new Player("Stella", PlayerType::AI));
$casino->buy_chips($player3, 1000);
$table->seat_player($player3, $table->seats[3])->buy_chips(1000);

$continue = true;
while ($continue) $continue = $table->new_hand();

foreach ($table->seats as $seat) $seat->cash_out();
foreach ($casino->players as $player) $casino->cash_out($player);
//print_r($table->chat_history);
