#!/usr/local/bin/php -f
<?php

namespace RPurinton\poker;

enum TableStatus: int
{
    case WAITING_FOR_PLAYERS = 0;
    case STARTING = 1;
    case PREFLOP = 2;
    case FLOP = 3;
    case TURN = 4;
    case RIVER = 5;
    case SHOWDOWN = 6;
    case HAND_OVER = 7;
    public function display(): string
    {
        return match ($this) {
            TableStatus::WAITING_FOR_PLAYERS => 'Waiting for players',
            TableStatus::STARTING => 'Starting',
            TableStatus::PREFLOP => 'Pre-flop',
            TableStatus::FLOP => 'Flop',
            TableStatus::TURN => 'Turn',
            TableStatus::RIVER => 'River',
            TableStatus::SHOWDOWN => 'Showdown',
            TableStatus::HAND_OVER => 'Hand over',
        };
    }
}
class Card
{
    public function __construct(
        private Suit $suit,
        private Rank $rank
    ) {
    }
    public function getSuit(): Suit
    {
        return $this->suit;
    }
    public function getRank(): Rank
    {
        return $this->rank;
    }
    public function __toString(): string
    {
        return $this->rank->display() . $this->suit->display();
    }
}
class Casino
{
    public array $tables = [];
    public array $players = [];
    public Pot $vault;
    public function __construct(
        private string $name
    ) {
        $this->vault = new Pot(0);
    }
    public function __toString(): string
    {
        return $this->name;
    }
    public function getName(): string
    {
        return $this->name;
    }
    public function setName(string $name): void
    {
        if (strlen($name) < 3) {
            throw new \Exception('Name must be at least 3 characters.');
        }
        $this->name = $name;
    }
    public function addTable(Table $table): Table
    {
        $this->tables[] = $table;
        return $table;
    }
    public function addPlayer(Player $player): Player
    {
        $this->players[] = $player;
        return $player;
    }
    public function depositToVault(float $amount): void
    {
        $this->vault->add($amount);
    }
    public function withdrawFromVault(float $amount): void
    {
        $this->vault->remove($amount);
    }
    public function buyChips(Player $player, float $amount): void
    {
        $this->depositToVault($amount);
        $player->getBankroll()->add($amount);
    }
    public function cashOut(Player $player): void
    {
        $this->withdrawFromVault($player->getBankroll()->getAmount());
        $player->getBankroll()->setAmount(0);
    }
    public function cashOutPartial(Player $player, float $amount): void
    {
        $this->withdrawFromVault($amount);
        $player->getBankroll()->remove($amount);
    }
}
class Seat
{
    private SeatStatus $status = SeatStatus::EMPTY;
    private ?Player $player = null;
    public array $cards = [];
    private Pot $stack;
    public function __construct()
    {
        $this->stack = new Pot(0);
    }
    public function getStatus(): SeatStatus
    {
        return $this->status;
    }
    public function setStatus(SeatStatus $status): void
    {
        $this->status = $status;
    }
    public function getPlayer(): ?Player
    {
        return $this->player;
    }
    public function setPlayer(Player $player): void
    {
        $this->player = $player;
    }
    public function getStack(): Pot
    {
        return $this->stack;
    }
    public function __toString(): string
    {
        return $this->player->getName();
    }
    public function clearCards(): void
    {
        $this->cards = [];
    }
    public function buyChips(float $amount): void
    {
        $amount = min($amount, $this->player->getBankroll()->getAmount());
        $this->player->getBankroll()->remove($amount);
        $this->stack->add($amount);
    }
    public function topUp(float $amount): void
    {
        $current_stack = $this->stack->getAmount();
        if ($current_stack < $amount) {
            $this->buyChips($amount - $current_stack);
        }
    }
    public function prompt(Table $table): void
    {
        switch ($this->player->type) {
            case PlayerType::HUMAN:
                echo ($this->player->getName() . "'s cards: [" . implode(', ', $this->cards) . "]\n");
                break;
            case PlayerType::BOT:
                echo ($this->player->getName() . "'s cards: [" . implode(', ', $this->cards) . "]\n");
                break;
        }
    }
}
enum PlayerStatus
{
    case STANDING;
    case WAITING_FOR_TABLE;
    case SEAT_RESERVED;
    case SEATED;
}
enum Suit
{
    case CLUBS;
    case DIAMONDS;
    case HEARTS;
    case SPADES;
    public function display(): string
    {
        return match ($this) {
            Suit::CLUBS => 'c',
            Suit::DIAMONDS => 'd',
            Suit::HEARTS => 'h',
            Suit::SPADES => 's',
        };
    }
    public static function toArray(): array
    {
        return [
            Suit::CLUBS,
            Suit::DIAMONDS,
            Suit::HEARTS,
            Suit::SPADES,
        ];
    }
}
enum PlayerType
{
    case HUMAN;
    case BOT;
}
enum SeatStatus
{
    case EMPTY;
    case RESERVED;
    case WAITING;
    case POSTED;
    case PLAYING;
    case SITOUT;
    case TIMEOUT;
    case FOLDED;
}
class HandEvaluator
{
}
enum Limit
{
    case NL;
    case PL;
    case FL;
    public function display(): string
    {
        return match ($this) {
            Limit::NL => 'NL',
            Limit::PL => 'PL',
            Limit::FL => 'FL',
        };
    }
    public static function toArray(): array
    {
        return [
            Limit::NL,
            Limit::PL,
            Limit::FL,
        ];
    }
}
class Deck
{
    private $cards = [];
    public function __construct()
    {
        $this->cards = $this->createDeck();
    }
    public function getCards()
    {
        return $this->cards;
    }
    public function shuffle()
    {
        shuffle($this->cards);
    }
    public function cut()
    {
        $cut = rand(1, 51);
        $this->cards = array_merge(
            array_slice($this->cards, $cut),
            array_slice($this->cards, 0, $cut)
        );
    }
    public function dealCard(array &$destination): void
    {
        $destination[] = array_pop($this->cards);
    }
    private function createDeck()
    {
        $cards = [];
        foreach (Suit::toArray() as $suit) {
            foreach (Rank::toArray() as $rank) {
                $cards[] = new Card($suit, $rank);
            }
        }
        return $cards;
    }
    public function toString()
    {
        $deck = '';
        foreach ($this->cards as $card) {
            $deck .= $card . ' ';
        }
        return $deck;
    }
}
class Pot
{
    private array $eligible = [];
    public function __construct(private float $amount = 0, public bool $good = true)
    {
        $this->amount = round($this->amount, 2);
    }
    public function add(float $amount): void
    {
        $this->amount += round($amount, 2);
    }
    public function remove(float $amount): void
    {
        $this->amount -= round($amount, 2);
    }
    public function getAmount(): float
    {
        return round($this->amount, 2);
    }
    public function setAmount(float $amount): void
    {
        $this->amount = round($amount, 2);
    }
    public function contribute(float $amount, Seat $seat)
    {
        $this->add($amount);
        $seat->getStack()->remove($amount);
        $this->eligible[] = $seat;
    }
    public function __toString(): string
    {
        return '$' . number_format($this->amount, 2, '.', ',');
    }
}
enum Rank: int
{
    case TWO = 2;
    case THREE = 3;
    case FOUR = 4;
    case FIVE = 5;
    case SIX = 6;
    case SEVEN = 7;
    case EIGHT = 8;
    case NINE = 9;
    case TEN = 10;
    case JACK = 11;
    case QUEEN = 12;
    case KING = 13;
    case ACE = 14;
    public function display(): string
    {
        return match ($this) {
            self::TWO => '2',
            self::THREE => '3',
            self::FOUR => '4',
            self::FIVE => '5',
            self::SIX => '6',
            self::SEVEN => '7',
            self::EIGHT => '8',
            self::NINE => '9',
            self::TEN => 'T',
            self::JACK => 'J',
            self::QUEEN => 'Q',
            self::KING => 'K',
            self::ACE => 'A',
        };
    }
    public static function toArray(): iterable
    {
        return [
            self::TWO,
            self::THREE,
            self::FOUR,
            self::FIVE,
            self::SIX,
            self::SEVEN,
            self::EIGHT,
            self::NINE,
            self::TEN,
            self::JACK,
            self::QUEEN,
            self::KING,
            self::ACE,
        ];
    }
}
enum GameType: int
{
    case TEXAS_HOLDEM = 1;
    case OMAHA = 2;
    case OMAHA_HILO = 3;
    public function display()
    {
        return match ($this) {
            GameType::TEXAS_HOLDEM => 'Texas Hold \'Em',
            GameType::OMAHA => 'Omaha',
            GameType::OMAHA_HILO => 'Omaha Hi/Lo',
        };
    }
    public function num_hole_cards()
    {
        return match ($this) {
            GameType::TEXAS_HOLDEM => 2,
            GameType::OMAHA, GameType::OMAHA_HILO => 4,
        };
    }
}
class Table
{
    public array $seats = [];
    private array $config = [
        "id" => null,
        "status" => TableStatus::WAITING_FOR_PLAYERS,
        "gametype" => GameType::TEXAS_HOLDEM,
        "seats" => 9,
        "smallBlind" => 1,
        "bigBlind" => 2,
        "limit" => Limit::NL,
        "minBuyIn" => 100,
        "maxBuyIn" => 1000,
        "straddles" => 0,
        "buttonstraddle" => false,
        "straddleAmount" => 4,
    ];
    public ?Deck $deck = null;
    public array $pots = [];
    public array $communityCards = [];
    public array $muck = [];
    private HandEvaluator $handEvaluator;
    private int $button_position = 0;
    private int $action_position = 0;
    public array $chat_history = [];
    public function __construct(array $config = [])
    {
        $this->config = array_merge($this->config, $config);
        $this->createSeats();
        $this->deck = new Deck();
        $this->handEvaluator = new HandEvaluator();
    }
    public function getSeats(): array
    {
        return $this->seats;
    }
    public function getGameType(): ?GameType
    {
        return $this->config['gametype'];
    }
    public function setGameType(GameType $gameType): void
    {
        $this->config['gametype'] = $gameType;
    }
    public function getConfig(): array
    {
        return $this->config;
    }
    public function setConfig(array $config): void
    {
        $this->config = array_merge($this->config, $config);
    }
    private function createSeats(): void
    {
        for ($i = 0; $i < $this->config['seats']; $i++) {
            $this->seats[] = new Seat();
        }
    }
    public function setStakes($minBuyIn, $maxBuyIn, $smallBlind, $bigBlind): void
    {
        $this->config['minBuyIn'] = $minBuyIn;
        $this->config['maxBuyIn'] = $maxBuyIn;
        $this->config['smallBlind'] = $smallBlind;
        $this->config['bigBlind'] = $bigBlind;
    }
    public function seatPlayer(Player $player, Seat $seat): Seat
    {
        $seat->setPlayer($player);
        $seat->setStatus(SeatStatus::WAITING);
        $player->setStatus(PlayerStatus::SEATED);
        return $seat;
    }
    public function reserveSeat(Player $player, Seat $seat): Seat
    {
        $seat->setPlayer($player);
        $seat->setStatus(SeatStatus::RESERVED);
        $player->setStatus(PlayerStatus::SEAT_RESERVED);
        return $seat;
    }
    public function new_hand(): void
    {
        $this->chat("Starting a new hand of " . $this->config["limit"]->display() . " " . $this->config['gametype']->display() . " [$" . $this->config['smallBlind'] . "/$" . $this->config['bigBlind'] . "]");
        $this->config['status'] = TableStatus::STARTING;
        $players_ready = $this->resetSeats();
        if ($players_ready < 2) {
            $this->chat("Not enough players to start a new hand.");
            return;
        }
        $this->muck = [];
        $this->communityCards = [];
        $this->pots = [];
        $this->pots[0] = new Pot(0, false);
        $this->advanceButton();
        $this->deck = new Deck();
        $this->action_position = $this->postBlinds();
        $this->deck->shuffle();
        $this->deck->cut();
        $this->dealHoleCards();
        $this->config['status'] = TableStatus::PREFLOP;
        $this->bettingRound();
    }
    private function bettingRound(): void
    {
        while (!$this->potsGood()) {
            $action_order = $this->getActionOrder();
            foreach ($action_order as $seat_number) {
                $seat = $this->seats[$seat_number];
                $seat->prompt($this);
            }
            $this->pots[0]->good = true;
        }
    }
    private function potsGood(): bool
    {
        foreach ($this->pots as $pot) {
            if (!$pot->good) return false;
        }
        return true;
    }
    private function getActionOrder(): array
    {
        $action_order = [];
        $seat_number = $this->action_position;
        while (true) {
            $seat_number++;
            if ($seat_number >= count($this->seats)) $seat_number = 0;
            $seat = $this->seats[$seat_number];
            if (in_array($seat->getStatus(), [SeatStatus::PLAYING, SeatStatus::POSTED])) $action_order[] = $seat_number;
            if ($seat_number == $this->action_position) break;
        }
        return $action_order;
    }
    private function dealHoleCards(): void
    {
        $deal_order = $this->getDealOrder();
        for ($i = 0; $i < $this->config["gametype"]->num_hole_cards(); $i++) {
            foreach ($deal_order as $seat_number) {
                $this->deck->dealCard($this->seats[$seat_number]->cards);
            }
        }
    }
    private function getDealOrder(): array
    {
        $deal_order = [];
        $seat_number = $this->button_position;
        while (true) {
            $seat_number++;
            if ($seat_number >= count($this->seats)) $seat_number = 0;
            $seat = $this->seats[$seat_number];
            if (in_array($seat->getStatus(), [SeatStatus::PLAYING, SeatStatus::POSTED])) $deal_order[] = $seat_number;
            if ($seat_number == $this->button_position) break;
        }
        return $deal_order;
    }
    private function postBlinds(): int
    {
        return $this->postBigBlind($this->postSmallBlind());
    }
    private function postSmallBlind(): int
    {
        $small_blind_amount = $this->config['smallBlind'];
        $small_blind_seat_number = $this->getNextActiveSeat($this->button_position);
        $small_blind_seat = $this->seats[$small_blind_seat_number];
        while ($small_blind_seat->getStack()->getAmount() < $small_blind_amount) {
            $small_blind_seat->setStatus(SeatStatus::SITOUT);
            $small_blind_seat_number = $this->getNextActiveSeat($this->button_position);
            $small_blind_seat = $this->seats[$small_blind_seat_number];
        }
        $this->pots[0]->contribute($small_blind_amount, $small_blind_seat);
        $small_blind_seat->setStatus(SeatStatus::POSTED);
        $this->chat($small_blind_seat->getPlayer()->getName() . " posts the small blind of $" . $small_blind_amount);
        return $small_blind_seat_number;
    }
    private function postBigBlind($small_blind_seat_number): int
    {
        $big_blind_amount = $this->config['bigBlind'];
        $big_blind_seat_number = $this->getNextActiveSeat($small_blind_seat_number);
        $big_blind_seat = $this->seats[$big_blind_seat_number];
        while ($big_blind_seat->getStack()->getAmount() < $big_blind_amount) {
            $big_blind_seat->setStatus(SeatStatus::SITOUT);
            $big_blind_seat_number = $this->getNextActiveSeat($this->button_position + 2);
            $big_blind_seat = $this->seats[$big_blind_seat_number];
        }
        $this->pots[0]->contribute($big_blind_amount, $big_blind_seat);
        $big_blind_seat->setStatus(SeatStatus::POSTED);
        $this->chat($big_blind_seat->getPlayer()->getName() . " posts the big blind of $" . $big_blind_amount);
        return $big_blind_seat_number;
    }
    private function advanceButton(): void
    {
                $this->button_position = $this->getNextActiveSeat($this->button_position);
    }
    private function getNextActiveSeat($seat): int
    {
        $seat++;
        if ($seat >= count($this->seats)) $seat = 0;
        if (!in_array($this->seats[$seat]->getStatus(), [SeatStatus::PLAYING, SeatStatus::POSTED])) $seat = $this->getNextActiveSeat($seat);
        return $seat;
    }
    public function resetSeats(): int
    {
        $players_ready = 0;
        foreach ($this->seats as $seat_number => $seat) {
            $seat->clearCards();
            switch ($seat->getStatus()) {
                case SeatStatus::WAITING:
                case SeatStatus::POSTED:
                case SeatStatus::FOLDED:
                case SeatStatus::PLAYING:
                    if ($seat->getStack()->getAmount() < $this->config['bigBlind']) $seat->setStatus(SeatStatus::SITOUT);
                    else {
                        $seat->setStatus(SeatStatus::PLAYING);
                        $seat->topUp($this->config['maxBuyIn']);
                        $this->chat("Seat $seat_number\t{$seat->getStack()}\t{$seat->getPlayer()->getName()}");
                        $players_ready++;
                    }
                    break;
                case SeatStatus::TIMEOUT:
                    $seat->setStatus(SeatStatus::SITOUT);
                    break;
                default:
                    break;
            }
        }
        return $players_ready;
    }
    public function chat($message)
    {
        $this->chat_history[] = $message;
        echo ($message . "\n");
    }
}
class Player
{
    private PlayerStatus $status = PlayerStatus::STANDING;
    private ?Pot $bankroll;
    public function __construct(
        private string $name,
        public PlayerType $type = PlayerType::HUMAN
    ) {
        $this->bankroll = new Pot(0);
    }
    public function getName(): string
    {
        return $this->name;
    }
    public function getBankroll(): Pot
    {
        return $this->bankroll;
    }
    public function setBankroll(Pot $bankroll): void
    {
        $this->bankroll = $bankroll;
    }
    public function setStatus(PlayerStatus $status): void
    {
        $this->status = $status;
    }
    public function __toString(): string
    {
        return $this->name;
    }
}
$casino = new Casino("My Casino");
$table = $casino->addTable(new Table([
    "id" => 1,
    "name" => "My Table",
]));
$player1 = $casino->addPlayer(new Player("Russell"), PlayerType::HUMAN);
$casino->buyChips($player1, 10000);
$table->seatPlayer($player1, $table->seats[0])->buyChips(1000);
$player2 = $casino->addPlayer(new Player("Lily"), PlayerType::BOT);
$casino->buyChips($player2, 10000);
$table->seatPlayer($player2, $table->seats[1])->buyChips(1000);
$table->new_hand();
